services:
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    restart: always
    volumes:
     - clickhouse_data:/var/lib/clickhouse
     - ./clickhouse-config.xml:/etc/clickhouse-server/config.d/custom.xml:ro,z
    networks:
      - flow-net
  flow-reciever:
    image:  pmacct/nfacctd:latest
    restart: always
    ports:
      - "2055:2055/udp"
    volumes:
      - ./nfacctd.conf:/etc/pmacct/nfacctd.conf:ro,z
      - ./netflow:/netflow:rw,z
    networks:
      - flow-net
    depends_on:
     - clickhouse
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=Qwe12345@!
      - GF_SECURITY_ADMIN_USER=dragun
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
    volumes:
      - grafana_datastorage:/var/lib/grafana
    networks:
      - flow-net
    depends_on:
      - clickhouse

networks:
  flow-net:
    driver: bridge

volumes:
  clickhouse_data:
  grafana_datastorage: