# Общие настройки
daemonize: false
pidfile: /var/run/nfacctd.pid

# Приём NetFlow (порт 2055 UDP)
nfacctd_port: 2055
nfacctd_ip: 0.0.0.0

# Агрегация данных (какие поля собирать и группировать)
#aggregate: src_host, dst_host, src_port, dst_port, proto, src_as, dst_as, bytes, packets, flows
#aggregate: src_host, dst_host, src_port, dst_port, proto, sum_bytes, sum_packets, flows
#aggregate: src_host, dst_host, src_port, dst_port, proto, src_as, dst_as, sum_bytes, sum_packets, flows
aggregate: src_host, dst_host, src_port, dst_port, proto

debug: true

plugins: print

print_output: json
print_output_file: /netflow/netflow.json
print_refresh_time: 60

# Производительность
plugin_buffer_size: 1024000
plugin_pipe_size: 1024000